### ISSUE TITLE
Which residual blocks are optimal to replace?

### ISSUE THREAD

**Issue by AlexeyAB** [TuSimple/simpledet#118]
@RogerChern Hi, Excellent work!

I want try to implement TridentNet with Yolo head. Can you clarify a few points?

1. Do you change Res-blocks to Trident-blocks only in Conv4_x, or in Conv5_x and Conv4_x?

2. Why did you change Res-blocks to Trident-blocks in ResNet-backbone instead of adding Trident-blocks after ResNet-backbone (in the 2nd case all Trident-blocks would be after the last subsampling-layer `stride=2` so an increase in dilatation would increase the receptive field **more**)?

3. What is the optimal number of Trident-blocks 10 or 15?

4. What is the optimal input network resolution?

----

Either
![1_aq0q7gCvuNUqnMHh4cpnIw - копия](https://user-images.githubusercontent.com/4096485/59159404-df42b680-8ad1-11e9-9495-76f5d51fb9c8.png) 

Or ![1_aq0q7gCvuNUqnMHh4cpnIw - копия (2)](https://user-images.githubusercontent.com/4096485/59159405-e4076a80-8ad1-11e9-95a5-7644149b1f9b.png)

----

https://arxiv.org/pdf/1901.01892v1.pdf

![image](https://user-images.githubusercontent.com/4096485/59159422-1dd87100-8ad2-11e9-9c5f-413cbdda2d78.png)

**Comment by RogerChern** [comment]
Hi @AlexeyAB , here are some thoughts about your questions.

1. Only conv4_x(a.k.a stage3_unitx) are converted into trident blocks. We use ResNet-C4 backbone and use conv5_x as the rcnn head. Adding trident blocks in the rcnn head is generally meaningless since you can not see beyond the cropped roi features. So put 10x trident blocks in conv4_x.

2. Changing resnet blocks to trident blocks allow us to utilize the imagenet pretrained models. This is a time-honored tradition as in NOC and deformable convnets. 

3. Adding more than 10 blocks gives a steady result.

4. If you are implementing YOLOv3, a 600x600 input is recommended. Otherwise, you need to tune the num of trident blocks to suit your need.

And if you are interested in YOLOv3, you can not miss the YOLOv3 implementation in GluonCV. They offer the pretrained models and [tons of fine details](https://arxiv.org/abs/1902.04103) to improve the performance of YOLOv3.

**Comment by AlexeyAB** [comment]
@RogerChern Thanks!
Yes, I know about GluonCV, and I use their Mixup-data-augmentation approach (Bag of Freebies): https://github.com/AlexeyAB/darknet/issues/3272#issuecomment-499298922
I just want to implement TridentNet on Darknet-framework(C) instead of Mxnet(Python).

Did you try to combine PANet and TridentNet, can it give any advantage?

**Comment by RogerChern** [comment]
@AlexeyAB Fusing multiple trident feature maps gives performance improvement over instance segmentation, but not detection.
