### ISSUE TITLE
why you use patch_config_as_nothrow function to convert ?

### ISSUE THREAD

**Issue by tieguanyin803** [TuSimple/simpledet#168]

**Comment by RogerChern** [comment]
Our config system is based on data class. The default behavior of referencing missing attribute is throwing `AttributeError`. This makes adding new config option painful because you need to wrap the new option in a try-catch block to provide a default value of the newly added option. After patching the config, now referencing a missing attribute returns `None` which can be chained as `None or default_value`. This is far more elegent compared with the original behevior.
