### ISSUE TITLE
Asking about singularity.

### ISSUE THREAD

**Issue by hungtran122** [TuSimple/simpledet#68]
Hello,

I tried to use singularity by following your instructions at "Install Singularity >= 2.6."
And I tried to bind the image as follow:
sudo singularity shell --no-home --nv -s /usr/bin/zsh --bind my_simpledet_dir /path/to/simpledet.img

then I tried to run this:
python3 detection_train.py --config config/tridentnet_r101v2c4_c5_multiscale_addminival_3x_fp16.py

It said: 
ImportError: No module named 'numpy'

then I tried to install pip3, numpy, mxnet1.3.1 and other dependencies. However I ended up having this error:
simpledet/models/tridentnet/builder.py", line 5, in <module>
ImportError: No module named 'mxnext'

In my understanding, this simpledet.img image should be set up the complete environment for this project. I don't know whether my understanding correct or not.
Could you please help me out?

**Comment by RogerChern** [comment]
Singularity provides all the **runtime** need to **run** simpledet. But you still need to setup simpledet separately since freeze it in the runtime image deny the meaning of future development.

As for your problem, please check the singularity image is properly loaded, `/path/to/simpledet.img` should be changed to the real path.
